rdkcentral/networkmanager

- LegacyPlugin_NetworkAPIs.cpp
- docs/NetworkManagerPlugin.md
Reason for change: Changed the default packet size of trace in the networkmanagerplugin.md to 5 and also added default packet size for ping in Legacynetworkplugin.cpp
Test Procedure: Build and verified
Risks: Low
Priority: P1
> DELIA-66037 - Trace and Ping ERROR_TIMEOUT response

- LegacyPlugin_NetworkAPIs.cpp
- LegacyPlugin_WiFiManagerAPIs.cpp
- NetworkManagerJsonRpc.cpp
Reason for change: Changed GetPariedSSID to return the last paired SSID instead of array and made changes to align with the NetworkManagerplugin.md documentation
Test Procedure: Build and verified
Risks: Low
Priority: P1
> DELIA-66281 - GetPariedSSID issue and aligning with the NetworkManagerPlugin.md documentation

- CMakeLists.txt
- LegacyPlugin_NetworkAPIs.conf.in
- LegacyPlugin_NetworkAPIs.config
- LegacyPlugin_NetworkAPIs.cpp
- LegacyPlugin_NetworkAPIs.h
- LegacyPlugin_WiFiManagerAPIs.conf.in
- LegacyPlugin_WiFiManagerAPIs.config
- LegacyPlugin_WiFiManagerAPIs.cpp
- LegacyPlugin_WiFiManagerAPIs.h
- NetworkManager.conf.in
- NetworkManager.config
- NetworkManager.cpp
- NetworkManager.h
- NetworkManagerJsonRpc.cpp
Reason for change:
- Use of SmartLinkType
- Use IPluginImpl to release ComRPC instance upon Deactivate
- Setup Startup Order to ensure NetworkManager is up before legacy plugins are activated
Test Procedure: Full Networking Verification
Risks: Low
> DELIA-66318 : Update NetworkManager Plugin

- NetworkManagerJsonRpc.cpp
Reason for change: In the input of getIPsettings, NULL is being passed for interface.
Allowing null interface also
Test Procedure: NA
Risks: Low
Priority: P1
> XIONE-15762 - [RDKE] [Xione]- Jumpserver access fails

- LegacyPlugin_NetworkAPIs.cpp
- LegacyPlugin_WiFiManagerAPIs.cpp
Reason for change: In the reported ticket, it is noticed that WiFi Plugin failed to subscribe `onAvailableSSIDs` event but didnt retry. So when scan is called by application, the scan was success but it never posted any update as it never received `onAvailableSSIDs` event from unified networkmanager plugin Test Procedure: As per DELIA-66411
Risks: Medium
> DELIA-66411 : Retry when subscription to an event failed

- LegacyPlugin_WiFiManagerAPIs.h
- NetworkManagerRDKProxy.cpp
Reason for change: Fixed the empty interface being returned in GetIPSettings
Test Procedure: as per DELIA-66721
Risks: Low
> DELIA-66721 : Fixed the empty interface being returned in GetIPSettings

- NetworkManagerRDKProxy.cpp
Reason for change: Removed the internal mapping and returning the actual strength value
Test Procedure: Check with curl command
Risks: Low
Priority: P1
> DELIA-66920 - GetWiFiSignalStrength is not return actual strength

- LegacyPlugin_WiFiManagerAPIs.cpp
- NetworkManagerRDKProxy.cpp
Reason for change: Below are the changes,
(1) The legacy plugin must return `"result":1` when failed as per the existing documentation. So added this change. (2) When WPS is initiated and wps failed at the RDKProxy, its returning RPC success but with the return param.status as failure. This has to be handled. Test Procedure: As per CELLO-352
Risks: Low
> CELLO-352 : Handle the WPS return code for RDKProxy & Legacy Plugin

- NetworkManagerGnomeWIFI.cpp
- NetworkManagerGnomeWIFI.h
Reason for change: Checking the SSID in the wpa_supplicant.conf file for wpa_cli connect complete. Also changed the wifi connect logic to use nmcli instead of calling wifiConnect API 
Test Procedure: startWPS curl command 
Risks: Medium
Priority: P0
> RDKEMW-540 - Changed the wpa_cli completed logic and wifi connect

- NetworkManagerImplementation.cpp
fix for Continuously, Box reboots with reboot reason MAINTENANCE_REBOOT, when the box is in Active Standby
> SERXIONE-6805 Box reboots with reboot reason MAINTENANCE_REBOOT, when the box is in Active Standby

- NetworkManager.h
DELIA-67124 : Handle the JSON Subscribe Event
Reason for change: The subscription request reached the NetworkManager and responded but due to the boot-up time no-cpu scenario, the success is NOT sent to consumer. So the consumer subscribes for the 2nd time, it returns already_exist error. It should be handled cleanly.
Test Procedure: As per DELIA-67124
Risks: Low
> DELIA-67124 : Handle the JSON Subscribe Event

- LegacyPlugin_WiFiManagerAPIs.cpp
Reason for change: Check if the ssid string is empty
Test Procedure: Build and verified
Risks: Low
Priority: P1
> RDK-55421 : Implement org.rdk.Wifi.retrieveSSID API

- NetworkManagerGnomeProxy.cpp
Reason for change: Modified the SetPrimaryInterface to return proper value in the success scenario
Test Procedure: Test and verified
Risks: Medium
Priority: P1
> RDKEMW-1849 - SetPrimaryInterface method returns failure

- INetworkManager.h
- LegacyPlugin_WiFiManagerAPIs.cpp
- LegacyPlugin_WiFiManagerAPIs.h
- NetworkManager.cpp
- NetworkManager.h
- NetworkManager.json
- NetworkManagerGnomeProxy.cpp
- NetworkManagerGnomeWIFI.cpp
- NetworkManagerImplementation.cpp
- NetworkManagerImplementation.h
- NetworkManagerJsonRpc.cpp
- NetworkManagerRDKProxy.cpp
- NetworkManagerStunClient.cpp
- Tests/raspberrypi/NetworkManagerGdbusTest.cpp
- Tests/unit_test/test_WiFiSignalStrengthMonitor.cpp
- docs/NetworkManagerPlugin.md
- gdbus/NetworkManagerGdbusClient.cpp
- gdbus/NetworkManagerGdbusClient.h
- gdbus/NetworkManagerGdbusProxy.cpp
- gdbus/NetworkManagerGdbusUtils.cpp
Reason for change:
1. Updated `GetWiFiSignalQuality` method to include SNR & Noise
2. Updated `onWiFiSignalQualityChange` event to include SNR & Noise.
3. Updated the documentation
4. Added logging for the instantiation and exit Test Procedure: Verify the APIs
Risks: Medium
Signed-off-by: kamirt573_comcast <karunakaran_amirthalingam@cable.comcast.com>
> RDK-56182 : Updated `GetWiFiSignalQuality` to include SNR

- NetworkManagerGnomeProxy.cpp
Reason for change: Temporary mitigation for GetPrimaryInterface failure
Test Procedure: Verify with curl commands
Risks: Low
Priority: P1
> RDKEMW-1928 - GetPrimaryInterface is returning false

- .github/workflows/rdk_unit_test.yml
- NetworkManagerConnectivity.cpp
- NetworkManagerImplementation.cpp
- NetworkManagerImplementation.h
Reason for change: Changed the initial monitoring logic to post the internet status change event even when we have single successful connect. Also changed the IPv4 and IPv6 thread start only when there is corresponding IPv4 and IPv6 are available
Test Procedure: Test and verified
Risks: Medium
Priority: P1
> RDKTV-35857 - Device is connected to Wi-Fi but not connected to internet because of curl error 28

- NetworkManagerConnectivity.cpp
- NetworkManagerImplementation.h
- NetworkManagerRDKProxy.cpp
Reason for change: Added log specific to few known scenarios which will help field triage team when issue is reported. Following metrics are added.
`INTERNET_CONNECTIVITY_MONITORING_CURL_ERROR`
`INTERNET_CONNECTIVITY_MONITORING_NO_INTERFACE_UP`
`INTERNET_CONNECTIVITY_MONITORING_NO_IP_ADDRESS`
`INTERNET_CONNECTIVITY_MONITORING_INITIAL_CHECK_ENTRY`
Test Procedure: Verify the logs 
Risks: Medium
Priority: P1
> RDKTV-36020 : Added Telemetry log for tracking the issue in field

- plugin/gnome/NetworkManagerGnomeEvents.cpp
- plugin/gnome/NetworkManagerGnomeEvents.h
- plugin/gnome/NetworkManagerGnomeProxy.cpp
- plugin/gnome/NetworkManagerGnomeUtils.cpp
- plugin/gnome/NetworkManagerGnomeUtils.h
- plugin/gnome/NetworkManagerGnomeWIFI.cpp
- RDKEMW-3249: GetInterfaceState API Returns Ethernet Enabled on Wi-Fi Only Devices
- RDKEMW-3191: Enabled NetworkManager DEBUG logs when SetLogLevel(DEBUG) Called
> RDKEMW-3249, RDKEMW-3191  Fix GetInterfaceState Reporting on Wi-Fi Only Devices & Enable NetworkManager DEBUG Logs via SetLogLevel(DEBUG)

- plugin/NetworkManagerImplementation.cpp
- plugin/NetworkManagerImplementation.h
Reason for change: Add Process Memory Monitoring thread which reads n prints the RSS & USS periodically every 1 min
Test Procedure: watch for RSS print in wpeframework.log
Risks: Medium
Signed-off-by: kamirt573_comcast <karunakaran_amirthalingam@cable.comcast.com>
> RDKEMW-3086 : Add Process Memory Monitoring

- plugin/NetworkManagerImplementation.cpp
Reason for change: Reading of /proc/PID/smaps is failing for some platforms; so lets use /proc/PID/statm as standard for now
Test Procedure: Grep the logs for RSS
Risks: Low
Signed-off-by: kamirt573_comcast <karunakaran_amirthalingam@cable.comcast.com>
> RDKEMW-3086 : Read /proc/PID/statm to print RSS

- NetworkManagerConnectivity.cpp
Reason for change: Removed the m_notify in the switchToInitialCheck(). As it is leads to a unnecessary event posting, while the connectivityMonitorFunction() is in regular connectivity monitoring and switchToInitialCheck is triggered by ReportInterfaceStateChange() 
Test Procedure: Verify the deep sleep scenario for connectivity
Risks: Medium
Priority: P1
> RDKTV-36195 - TV is taking 8-20 seconds to get stable internet connection after waking up from Deepsleep

- NetworkManagerConnectivity.cpp
- NetworkManagerRDKProxy.cpp
Reason for change: To address the scenario of IPv6 lost after the device wakeup from deepsleep and has only IPv4. Currenlty, we are getting IPv6 as default IP Address which resulted in this issue. Enhanced the logic to get both IPv4 and IPv6 in GetInitialConnectionState() to address this issue.
Test Procedure: As mentioned in the jira ticket RDKTV-36415
Risks: Medium
Priority: P0
> RDKTV-36415 - Device is taking 3-5min to connect the internet after waking from DS

- plugin/NetworkManagerImplementation.cpp
Reason for change: Added try catch to detect whether crash is happening in monitorThreadFunction function
Test Procedure: Check for the logs monitorThreadFunction 
Risks: Medium
Priority: P2
> RDKEMW-4100 - [RDKEMW][FOXTEL] [XioneUK] Process crashed = NetworkManager seen on after reboot

- NetworkManagerImplementation.cpp
Reason for change: Initiating the switchToInitialCheck() only when the interface is up so that we won't miss the onInternetStatusChange event 
Test Procedure: Check the timing to get connected to internet after waking from deep sleep
Risks: Medium
Priority: P1
> RDKTV-36771 - Hisense V2 devices take 5-10s more to get connected

- plugin/NetworkManagerImplementation.cpp
Reason for change: Losing WiFi Signal Monitor Thread context when Toggling WiFi - Leading to exception
Test Procedure: Network Reset
Risks: Low
> RDKEMW-4095 : Losing WiFi Signal Monitor Thread context when Toggling WiFi - Leading to exception

- NetworkManagerRDKProxy.cpp
Reason for change: Posting the events only for ethernet when both the interfaces
are connected
Test Procedure: Deep sleep to wake scenario
Risks: Medium
Priority: P1
> RDKTV-37172 - Avoid DefaultInterfaceChanged event to report WiFi as new interface

- LegacyPlugin_WiFiManagerAPIs.cpp
Reason for change: Changes the retieveSSID security mode return value as per legacy getsupportedsecuritymodes
Test Procedure: retrieveSSID curl command
Risks: Medium
Priority: P1
> RDKTV-37227 - retrieveSSID API should return the Security Mode

- plugin/rdk/NetworkManagerRDKProxy.cpp
Reason for change: The issue is because of the logic failure is in accessing the InterfaceList Iterator returned by the Thunder IIteratorType. Addressed the same by resetting the list with Reset() call. Also moved the interface count while loop inside the return code and NULL pointer check Test Procedure: Deep sleep to wake up scenario
Priority:P1
Risks: Medium
> RDKTV-37469, RDKTV-37468 - Increase in offline toaster markers

- .vscode/settings.json
- plugin/NetworkManagerImplementation.cpp
Reason for Change:
- ping succeeds with invalid ipversion
```
{"jsonrpc":"2.0","id":42,"method":"org.rdk.NetworkManager.1.Ping","params":{"endpoint":"142.250.192.78","ipversion":"invalid"}}
{"jsonrpc":"2.0","id":42,"method":"org.rdk.NetworkManager.1.Trace","params":{"endpoint":"45.57.221.20","ipversion":"abcd","packets":10,"guid":"b0f2f648-de5d-4e71-97a7-685cea75ad9a"}}
```
- SetStunEndPoint responds SUCCESS for invalid input
```
{"jsonrpc":"2.0","id":42,"method":"org.rdk.NetworkManager.1.SetStunEndpoint"}
{"jsonrpc":"2.0","id":42,"method":"org.rdk.NetworkManager.1.SetStunEndpoint","params":{"port":0}}
```
> RDKEMW-2939: add param validation

- plugin/rdk/NetworkManagerRDKProxy.cpp
Reason for change: multiple IP change event is posting while ethernet and Wi-Fi connecting
Test Procedure: Verify Skyxione and Xumo devices
Priority: P1
> RDKEMW-5550 Multiple IP address change events with IPv6/IPV4 after network link up

- plugin/gnome/NetworkManagerGnomeEvents.cpp
Reason for change: Posting the WIFI connected event when we receive the state as NM_DEVICE_STATE_IP_CONFIG from gnome networkmanager so that we can avoid the delay in postin the events onWiFiStateChanged Test Procedure: Network reset with UI
Priority:P1
Risks: Medium
> RDKEMW-6063 - OnWiFiStateChanged Event is not posted appropriately wlan0 LINK_UP

- NetworkManagerImplementation.cpp
Reason for change: The issue is happening because of the race condition happening between the 2 threads(connectivityMonitorFunction and the main thread in which switchToInitialCheck executes). Because of the race condition, switchToInitialCheck() was triggered before the m_wlanConnected was set to true. So the execution goes inside [else if (_instance != nullptr && !_instance->m_ethConnected && !_instance->m_wlanConnected)] and no event is actually posted as InitialRetryCount was already set to 1. Made changes to ReportInterfaceStateChange() to set m_wlanConnected to true when the interface is UP and then switchToInitialCheck() is triggered. Test Procedure: Deep sleep to wake up scenario
Priority:P1
Risks: Medium
> RDKTV-37660 - TVOffline marker seen after waking up due to Roam event and IP acquisition delay

- plugin/NetworkManagerImplementation.cpp
Reason for change: fix for connectivity monitor crash
Test Procedure: reboot test and verify the crash
> RDKEMW-7458 Connectivity monitor Thread crashed during Reboot

- plugin/NetworkManagerImplementation.cpp
- plugin/NetworkManagerImplementation.h
- plugin/rdk/NetworkManagerRDKProxy.cpp
- tests/l2Test/l2_test_rdkproxy.cpp
Reason for change: Clamp Network-Plugin Noise Value to Range [0 dBm to -96dBm]
some of the devices reporting a static noise value as (-117db)
> RDKEMW-7459 : Clamp Network-Plugin Noise Value to Range [0 dBm to -96dBm]

- plugin/gnome/gdbus/NetworkManagerGdbusClient.cpp
Reason for change: Removed the secrets stored as the comments 
Test Procedure: Verify the build is successful
Priority:P0
Risks: Medium
> RDKEMW-7736 : Comments Cleanup in NetworkManager Plugin (#218)

- interface/INetworkManager.h
- plugin/NetworkManager.h
- plugin/NetworkManagerConnectivity.cpp
- plugin/NetworkManagerConnectivity.h
- plugin/NetworkManagerImplementation.cpp
- plugin/NetworkManagerImplementation.h
- plugin/NetworkManagerJsonRpc.cpp
- tests/l1Test/l1_test_connectivity.cpp
- tests/l2Test/rdk/CMakeLists.txt
- tests/l2Test/rdk/l2_test_rdkproxyEvent.cpp
- tests/mocks/CurlWraps.cpp
- tests/mocks/CurlWraps.h
- tests/mocks/CurlWrapsMock.h
- tools/plugincli/NetworkManagerGdbusTest.cpp
- tools/plugincli/NetworkManagerLibnmTest.cpp
Reason for change: Internet Monitoring to be supported Ethernet & WiFi independently
Test Procedure: Verify connectivity in all the platforms
Priority: P1
Risks: Medium
> RDK-57174: Enhance the Internet Monitoring to be supported for Ethernet & WiFi independently
