rdkcentral/networkmanager

LegacyPlugin_NetworkAPIs.cpp, LegacyPlugin_WiFiManagerAPIs.cpp, NetworkManagerGnomeEvents.cpp, NetworkManagerGnomeEvents.h, NetworkManagerGnomeProxy.cpp, NetworkManagerGnomeUtils.cpp, NetworkManagerGnomeUtils.h, NetworkManagerGnomeWIFI.cpp, NetworkManagerGnomeWIFI.h
Fix for Gnome crashed
Case insensitive comparison added in legacy networkmanager
=> DELIA-66248, RDKTV-32911 : fix for Fix Network Manager plugin crash in gnome and RDK platform Error 

CMakeLists.txt, CONTRIBUTING.md, NetworkManagerImplementation.cpp, NetworkManagerLogger.cpp, NetworkManagerRDKProxy.cpp, README.md, cmake/Findrdklogger.cmake
Reason for change: Implement RDKLogger Support to NetworkManager Plugin
Test Procedure: Verify logs are printed properly
Risks: Low
=> DELIA-66446 : Implement RDKLogger Support to NetworkManager Plugin

docs/NetworkManagerPlugin.md
Updated the documentation for external interfaces
=> Updated the documentation for external interfaces

NetworkManager.json, NetworkManagerJsonRpc.cpp, NetworkManagerRDKProxy.cpp, docs/NetworkManagerPlugin.md
DELIA-66644 : Updated documentation & GetIPSettings return value
=> DELIA-66644 : Updated documentation & GetIPSettings return value

LegacyPlugin_NetworkAPIs.cpp
Reason for change: Fixed the empty IPAddress in onIPAddressChange Event
Test Procedure: as per DELIA-66775 
Risks: Medium
=> DELIA-66775 : Handle onIPAddressChange Event

.github/workflows/fossid_integration_stateless_diffscan_target_repo.yml
Implement Fossid Scan to NetworkManager
=> Implement Fossid Scan to NetworkManager

.github/workflows/gnome_unit_test.yml, CMakeLists.txt, NetworkManagerConnectivity.cpp, NetworkManagerConnectivity.h, NetworkManagerGnomeProxy.cpp, NetworkManagerImplementation.cpp, NetworkManagerImplementation.h, NetworkManagerRDKProxy.cpp, Tests/unit_test/test_NetworkManagerConnectivity.cpp, Tests/unit_test/test_NetworkManagerStunClient.cpp, Tests/unit_test/test_WiFiSignalStrengthMonitor.cpp, Tests/unit_test/unit_tests.cmake
modify the interface status logic
=> DELIA-66968 Disable continuous connectivity monitor when Interface is disconnected

NetworkManagerGnomeProxy.cpp, NetworkManagerGnomeWIFI.cpp
Reason for change: Fixed WPS issue with EPG on factory reset
Test Procedure: Verify the WPS functionality with EPG on factory reset
Risks: Medium
Priority: P0
=> RDKE-352 - Fixed WPS issue with EPG on factory reset

INetworkManager.h, NetworkManagerImplementation.cpp, NetworkManagerImplementation.h, NetworkManagerJsonRpc.cpp, NetworkManagerStunClient.cpp, NetworkManagerStunClient.h
Reason for change: Replace Printf with NMLOG
Test Procedure: Test `"org.rdk.NetworkManager.GetPublicIP"`
Risks: Low
Signed-off-by: kamirt573_comcast <karunakaran_amirthalingam@cable.comcast.com>
=> RDKEMW-892 : Replace Printf with NMLOG

CMakeLists.txt, INetworkManager.h, LegacyPlugin_NetworkAPIs.cpp, LegacyPlugin_NetworkAPIs.h, LegacyPlugin_WiFiManagerAPIs.cpp, NetworkManager.cpp, NetworkManager.json, NetworkManagerImplementation.cpp, NetworkManagerImplementation.h, NetworkManagerJsonRpc.cpp, NetworkManagerRDKProxy.cpp
Reason for change: Code Enhancements to the NetworkManager Plugin
Test Procedure: Sanity Testing
Risks: Medium
=> Code Enhancements to the NetworkManager Plugin

CMakeLists.txt
-D ENABLE_GNOME_GDBUS support added
=> Gdbus implementation compilation flag added

NetworkManagerConnectivity.cpp, NetworkManagerConnectivity.h, NetworkManagerLogger.cpp, NetworkManagerRDKProxy.cpp, NetworkManagerStunClient.cpp, WiFiSignalStrengthMonitor.h
Reason for change: For addressing the network manager coverity issues
Test Procedure: Build and verified with curl commands
Risks: Low
Priority: P1
Signed-off-by: Gururaaja ESR<Gururaja_ErodeSriranganRamlingham@comcast.com>
=> RDKEMW-1271 - Address coverity issues

NetworkManagerGnomeWIFI.cpp
Reason for change: Checked the ssid string is empty before finding the pattern in the file
Test Procedure: Build and verified with ubuntu desktop Risks: Low
Priority: P1
Signed-off-by: Gururaaja ESR Gururaja_ErodeSriranganRamlingham@comcast.com
=> wpsAction() function modification

NetworkManagerGnomeWIFI.cpp, NetworkManagerImplementation.cpp, NetworkManagerRDKProxy.cpp
- Remove platfom init thread logic
- nm_remote_connection_delete_async call replaced with nm_remote_connection_delete
=> RDKEMW-1412 Unable to see Wifi Scan results on UI

.github/workflows/gnome_unit_test.yml, .github/workflows/rdk_unit_test.yml, Tests/mocks/Iarm.cpp, Tests/mocks/Iarm.h, Tests/mocks/IarmBusMock.h, Tests/mocks/thunder/COMLinkMock.h, Tests/mocks/thunder/DispatcherMock.h, Tests/mocks/thunder/FactoriesImplementation.h, Tests/mocks/thunder/Module.cpp, Tests/mocks/thunder/Module.h, Tests/mocks/thunder/ServiceMock.h, Tests/mocks/thunder/SystemInfo.h, Tests/mocks/thunder/ThunderPortability.h, Tests/mocks/thunder/WorkerPoolImplementation.h, Tests/patches/thunder/Remove-SmartLinkType.patch, Tests/unit_test/test_LegacyPlugin_NetworkAPIs.cpp, Tests/unit_test/test_LegacyPlugin_WiFiManagerAPIs.cpp, Tests/unit_test/test_NetworkManager.cpp, Tests/unit_test/unit_tests.cmake
Updated unittest code to have L1 test cases
=> Updated unittest code to have L1 test cases

CMakeLists.txt, NetworkManagerGnomeEvents.cpp, NetworkManagerGnomeProxy.cpp, NetworkManagerGnomeUtils.cpp, NetworkManagerGnomeWIFI.cpp, NetworkManagerGnomeWIFI.h, NetworkManagerSecretAgent.cpp, NetworkManagerSecretAgent.h
1. implemented secret agent
2. fix for nmUtils::wifiSecurityModeFromAp function
=> RDKEMW-1447 Create user secret Agent for wps connection

NetworkManagerGnomeProxy.cpp, NetworkManagerImplementation.cpp, NetworkManagerImplementation.h, NetworkManagerRDKProxy.cpp, gdbus/NetworkManagerGdbusClient.cpp, gdbus/NetworkManagerGdbusProxy.cpp
Reason for change: Modified the GetWifiSignalStrength to read from the
wpa_cli command and extract the values out of it
Test Procedure: Test and verified
Risks: Medium
Priority: P1
=> RDK-55734 - NetworkManager Thunder Plugin - Report WiFi SNR

NetworkManagerGnomeWIFI.cpp
Remove NMSettingWirelessSecurity configuration form open wifi
=> RDKEMW-1848: Fail to connect to open wifi endpoints

INetworkManager.h, LegacyPlugin_NetworkAPIs.cpp, NetworkManager.json, NetworkManagerConnectivity.cpp, NetworkManagerConnectivity.h, NetworkManagerImplementation.cpp, NetworkManagerImplementation.h, NetworkManagerJsonRpc.cpp, docs/NetworkManagerPlugin.md
- modify isConnected To internet api to support both eth0 and wlan0
=> RDK-55586 Bring up both WiFi and Ethernet Interface

.github/workflows/gnome_unit_test.yml, CMakeLists.txt, gdbus/NetworkManagerGdbusClient.cpp, gdbus/NetworkManagerGdbusClient.h, gdbus/NetworkManagerGdbusProxy.cpp, gdbus/NetworkManagerGdbusUtils.cpp
- workflow updated to build gdbus proxy also
- add wps support in wificonnect api
- security agent support added
- security mode util unction updated
- getInitialConnectionState function added
=> RDKEMW-1808 [RDE] - Implement GNOME support via direct G-DBus WPS APIs

plugin/NetworkManagerSecretAgent.cpp, plugin/NetworkManagerSecretAgent.h, plugin/gnome/NetworkManagerGnomeEvents.cpp, plugin/gnome/NetworkManagerGnomeProxy.cpp, plugin/gnome/NetworkManagerGnomeWIFI.cpp
- Fix for WPS event not posting
- GetConnectedSSIDinfo return when device state fully activated state only
=> RDKEMW-1447, RDKEMW-2788, RDKEMW-2666  WPS - Screen is stuck Issue

legacy/LegacyWiFiManagerAPIs.cpp, plugin/NetworkManagerImplementation.cpp, plugin/NetworkManagerImplementation.h, plugin/NetworkManagerJsonRpc.cpp, plugin/NetworkManagerLogger.cpp, plugin/gnome/NetworkManagerGnomeUtils.cpp, plugin/gnome/NetworkManagerGnomeUtils.h, plugin/gnome/NetworkManagerGnomeWIFI.cpp, plugin/gnome/gdbus/NetworkManagerGdbusUtils.cpp, plugin/gnome/gdbus/NetworkManagerGdbusUtils.h
- Update the method used to detect open SSID
- Print the Discovered SSIDs in format
- Print the WIFI Security Mode detected as INFO
=> Update the method to Identify Open SSIDs

legacy/LegacyNetworkAPIs.cpp, plugin/NetworkManagerImplementation.cpp, plugin/NetworkManagerJsonRpc.cpp, plugin/gnome/NetworkManagerGnomeEvents.cpp, plugin/gnome/NetworkManagerGnomeProxy.cpp, plugin/gnome/NetworkManagerGnomeUtils.cpp, plugin/gnome/NetworkManagerGnomeUtils.h, plugin/gnome/NetworkManagerGnomeWIFI.cpp
- fix for wifi initial connection failure
- remove some info logs
=> RDKEMW-3088 WiFiConnect api getting failed at first time

plugin/NetworkManagerImplementation.h, plugin/gnome/NetworkManagerGnomeProxy.cpp, plugin/gnome/NetworkManagerGnomeWIFI.cpp, plugin/gnome/NetworkManagerGnomeWIFI.h, plugin/gnome/gdbus/NetworkManagerGdbusClient.h
Reason for change: Changed the way of setting primary interface from autoconnect priority to route metric
Test Procedure: Check with GetPrimaryInterface and SetPrimaryInterface curl commands
Risks: Medium
Priority: P1
=> RDKEMW-2191 - GetPrimaryInterface is returning wrong value for wlan0

plugin/NetworkManagerJsonRpc.cpp
- update internet subsystem update logic
=> RDKEMW-3561 Internet precondition is not satisfied by networkmanager

legacy/LegacyNetworkAPIs.cpp
Reason for change: Handle the response of PING request
Test Procedure: verify jsonrpc response for ping request
Risks: Low
=> DELIA-67975 : Handle the response of PING request

plugin/NetworkManagerImplementation.h, plugin/gnome/NetworkManagerGnomeProxy.cpp, plugin/gnome/NetworkManagerGnomeWIFI.cpp, plugin/gnome/NetworkManagerGnomeWIFI.h, plugin/gnome/gdbus/NetworkManagerGdbusClient.h
Refer- https://github.com/rdkcentral/networkmanager/pull/138/
=> RDKEMW-4731: GetPrimaryInterface is returning wrong value for wlan0

legacy/LegacyNetworkAPIs.cpp, plugin/NetworkManagerJsonRpc.cpp
Log the JSONRPC response for tracking purpose
=> Log the JSONRPC response for tracking purpose

definition/NetworkManager.json, docs/NetworkManagerPlugin.md, plugin/NetworkManagerImplementation.cpp, plugin/NetworkManagerImplementation.h, plugin/NetworkManagerJsonRpc.cpp
Reason for change: Modified the documentation for GetSupportedSecurityModes
Test Procedure: NA
Risks: Medium
Priority: P2
=> RDKEMW-4954 - NetworkManager plugin documentation change

.github/workflows/gnome_unit_test.yml, .github/workflows/rdk_unit_test.yml
Reason for change: Removed release and feature branches. Added support and topic branches.
Test Procedure: Check the .yml is getting executed for new added branches Risks: Medium
Priority: P2
=> RDKEMW-5110 - Updating the workflow of Network Manager plugin

CMakeLists.txt, Tests/unit_test/test_UpnpDiscoveryManager.cpp, Tests/unit_test/unit_tests.cmake, cmake/FindT2.cmake, tools/CMakeLists.txt, tools/upnp/CMakeLists.txt, tools/upnp/UpnpDiscoveryManager.cpp, tools/upnp/UpnpDiscoveryManager.h, tools/upnp/scripts/getRouterInfo-NMdispatcher.sh, tools/upnp/scripts/getRouterInfo-nlmon.sh, tools/upnp/scripts/readyToGetRouterInfo.sh, tools/upnp/scripts/routerDiscovery@.service
Reason for change: Using gupnp library to fetch gateway details
Test Procedure: Gateway details will be available in log file
Risks: Low
Signed-off-by: jincysaramma_sam@comcast.com
=> RDK-56442: Integrate UPNP to NetworkManagerPlugin

plugin/gnome/NetworkManagerGnomeEvents.cpp, plugin/gnome/NetworkManagerGnomeEvents.h, tests/l2Test/libnm/CMakeLists.txt, tests/l2Test/libnm/l2_test_libnmproxyEvent.cpp, tests/l2Test/libnm/l2_test_libnmproxyWifi.cpp, tests/l2Test/rdk/l2_test_rdkproxyEvent.cpp, tests/mocks/GLibWraps.cpp, tests/mocks/GLibWraps.h, tests/mocks/GLibWrapsMock.h, tests/mocks/LibnmWraps.cpp, tests/mocks/LibnmWraps.h, tests/mocks/LibnmWrapsMock.h
=> RDKEMW-6135 Implement L1/L2 for Legacy NetworkManager libnm Implementation
